import {
  faArrowLeft,
  faArrowRight,
  faArrowUpRightFromSquare,
  faBars,
  faBriefcase,
  faBuilding,
  faCode,
  faCompass,
  faDatabase,
  faDesktop,
  faEnvelope,
  faGears,
  faGraduationCap,
  faLanguage,
  faLayerGroup,
  faLocationDot,
  faMoon,
  faPlane,
  faServer,
  faShieldHalved,
  faStar,
  faSun,
  faTerminal,
  faTrophy,
  faUniversity,
  faWandMagicSparkles,
  faWrench,
  faXmark,
} from '@fortawesome/free-solid-svg-icons'
import { faGithub, faLinkedin } from '@fortawesome/free-brands-svg-icons'
import type { IconDefinition } from '@fortawesome/fontawesome-svg-core'
import type { IconName } from '../types'

export const iconRegistry = {
  university: faUniversity,
  plane: faPlane,
  building: faBuilding,
  compass: faCompass,
  code: faCode,
  monitor: faDesktop,
  server: faServer,
  database: faDatabase,
  gears: faGears,
  shield: faShieldHalved,
  wrench: faWrench,
  layers: faLayerGroup,
  magic: faWandMagicSparkles,
  arrowRight: faArrowRight,
  arrowLeft: faArrowLeft,
  external: faArrowUpRightFromSquare,
  envelope: faEnvelope,
  location: faLocationDot,
  moon: faMoon,
  sun: faSun,
  language: faLanguage,
  graduation: faGraduationCap,
  briefcase: faBriefcase,
  trophy: faTrophy,
  terminal: faTerminal,
  star: faStar,
  github: faGithub,
  linkedin: faLinkedin,
  bars: faBars,
  xmark: faXmark,
} satisfies Record<IconName, IconDefinition>

export function resolveIcon(name: IconName): IconDefinition {
  return iconRegistry[name]
}